/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;


#if !SILVERLIGHT
[Serializable]
#endif
public partial class SVHNQuery : TBase
{
  private string _filename;
  private byte[] _image;

  public string Filename
  {
    get
    {
      return _filename;
    }
    set
    {
      __isset.filename = true;
      this._filename = value;
    }
  }

  public byte[] Image
  {
    get
    {
      return _image;
    }
    set
    {
      __isset.image = true;
      this._image = value;
    }
  }


  public Isset __isset;
  #if !SILVERLIGHT
  [Serializable]
  #endif
  public struct Isset {
    public bool filename;
    public bool image;
  }

  public SVHNQuery() {
  }

  public void Read (TProtocol iprot)
  {
    iprot.IncrementRecursionDepth();
    try
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Filename = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              Image = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }
    finally
    {
      iprot.DecrementRecursionDepth();
    }
  }

  public void Write(TProtocol oprot) {
    oprot.IncrementRecursionDepth();
    try
    {
      TStruct struc = new TStruct("SVHNQuery");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Filename != null && __isset.filename) {
        field.Name = "filename";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Filename);
        oprot.WriteFieldEnd();
      }
      if (Image != null && __isset.image) {
        field.Name = "image";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Image);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }
    finally
    {
      oprot.DecrementRecursionDepth();
    }
  }

  public override string ToString() {
    StringBuilder __sb = new StringBuilder("SVHNQuery(");
    bool __first = true;
    if (Filename != null && __isset.filename) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Filename: ");
      __sb.Append(Filename);
    }
    if (Image != null && __isset.image) {
      if(!__first) { __sb.Append(", "); }
      __first = false;
      __sb.Append("Image: ");
      __sb.Append(Image);
    }
    __sb.Append(")");
    return __sb.ToString();
  }

}

