/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "svhn_constants.h"



const svhnConstants g_svhn_constants;

svhnConstants::svhnConstants() {
}



