/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef svhn_CONSTANTS_H
#define svhn_CONSTANTS_H

#include "svhn_types.h"



class svhnConstants {
 public:
  svhnConstants();

};

extern const svhnConstants g_svhn_constants;



#endif
